version: '3.8'

services:
  astro:
    build: ./
    # command: ./astro
    command: ./wait-for-postgres.sh db ./astro
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      - API_KEY=HPlhQWT8ri9yfZuAkZVh4ZEaUTCoBJbZcMynsHdP

      - DB_PASSWORD=qwerty
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_NAME=postgres
      - DB_SSLMODE=disable

  db:
    restart: always
    image: postgres:latest
    volumes:
    - ./.database/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=qwerty
    ports:
      - 5432:5432
